# Numpy
    Import numpy

In [3]:
import numpy as np

### Vactor Array Value

In [4]:
list_value = [1,2,3,4,5]
numpy_value = np.array(list_value)
numpy_value

array([1, 2, 3, 4, 5])

### Matrix Array Value

In [6]:
matrix_list = [[1,2,3], [4,5,6], [7, 8,9]]
matrix_array = np.array(matrix_list)
matrix_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Reshape Dimension

In [7]:
matrix_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
reshape_dimension = matrix_array.reshape(9,1)
reshape_dimension

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### Numpy arange()

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Step Up arange()

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Numpy zeros() & ones()

Vector value

In [18]:
ones = np.ones(3)
zeros = np.zeros(3)
zeros, ones

(array([0., 0., 0.]), array([1., 1., 1.]))

Matrix value

In [19]:
ones = np.ones([3,3])
zeros = np.zeros([3,3])
zeros, ones

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

### Numpy linspace() 
    generate value in range

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [27]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### Identity Martrix 

In [29]:
np.eye(3) , np.eye(4)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Numpy Random

Random 0 to 1

In [52]:
np.random.rand(10) , np.random.rand(3,3)

(array([0.49663584, 0.09423619, 0.49669792, 0.40190765, 0.04182109,
        0.98697225, 0.36307573, 0.84171237, 0.97649502, 0.24281855]),
 array([[0.39743816, 0.27729138, 0.31832689],
        [0.20786979, 0.52209085, 0.02893711],
        [0.89992121, 0.19144514, 0.18387899]]))

Random -1 to 1

In [35]:
np.random.randn(10), np.random.randn(3,3)

(array([ 0.19374935, -0.57340381, -0.10623877, -2.58602735, -1.1388741 ,
        -0.54938555,  1.07708385, -1.3180456 ,  1.25286505,  0.96153471]),
 array([[ 0.42769059, -0.21922264, -0.53557728],
        [ 0.25675108, -0.82391562, -0.13077006],
        [-0.28056124,  0.72993978,  0.66852928]]))

Random integer value 

In [50]:
np.random.randint(0,10), np.random.randint(0,10,20), np.random.randint(0,10,[10,10])

(2,
 array([1, 4, 5, 0, 0, 0, 7, 8, 6, 5, 1, 4, 6, 3, 6, 8, 8, 5, 0, 0]),
 array([[2, 4, 4, 4, 8, 8, 9, 1, 3, 1],
        [1, 6, 0, 0, 0, 8, 3, 7, 9, 1],
        [1, 0, 2, 6, 5, 2, 4, 0, 7, 7],
        [6, 9, 4, 1, 6, 7, 0, 1, 7, 0],
        [3, 6, 2, 8, 4, 1, 5, 6, 8, 7],
        [9, 4, 4, 8, 8, 8, 1, 1, 8, 4],
        [3, 4, 7, 3, 3, 9, 1, 1, 6, 5],
        [1, 6, 7, 0, 5, 8, 8, 8, 2, 2],
        [1, 0, 7, 0, 4, 0, 4, 7, 6, 4],
        [5, 4, 3, 8, 1, 9, 0, 3, 7, 7]]))

### Max and Min

In [75]:
arr = np.random.randint(1,11,[3,3])
arr, f'max : {arr.max()} , min : {arr.min()}'

(array([[10,  8, 10],
        [ 4,  2,  9],
        [ 1,  5,  1]]),
 'max : 10 , min : 1')

Find index 

In [76]:
arr

array([[10,  8, 10],
       [ 4,  2,  9],
       [ 1,  5,  1]])

In [78]:
arr.argmax(), arr.argmin()

(0, 6)

### Show shape

In [87]:
arr = np.array(np.random.randint(0,100,[4,4]))
arr

array([[47, 95, 20, 70],
       [89, 64, 48, 49],
       [60, 67, 98, 11],
       [ 1, 69, 43,  8]])

In [88]:
arr.shape

(4, 4)

In [94]:
arr = arr.reshape(2,8)
arr.shape

(2, 8)

### Numpy Indexing and Selection

indexgin

In [95]:
arr = np.array(np.arange(0,10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr[2]

2

In [97]:
arr[0:5]

array([0, 1, 2, 3, 4])

Boardcasting

In [98]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr[:] = 10
arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [103]:
arr[4:6] = 1000
arr

array([  10,   10,   10,   10, 1000, 1000,   10,   10,   10,   10])

### Memory in array 
    Must use .copy() if you don't want to change value in array and list

In [108]:
arr = np.arange(1,11)
new_arr = arr
new_arr[2] = 10
print(arr)
print(new_arr)

[ 1  2 10  4  5  6  7  8  9 10]
[ 1  2 10  4  5  6  7  8  9 10]


    PLEASE USE .copy() 

In [109]:
arr = np.arange(1,11)
new_arr = arr.copy()
new_arr[2] = 10
print(arr)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2 10  4  5  6  7  8  9 10]


### Numpy Indexing 2 Dimension

In [110]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

    arr[row][col]

In [111]:
arr[1][0]

4

In [117]:
arr[2:][0]

array([7, 8, 9])

In [126]:
arr[1:][0:]

array([[4, 5, 6],
       [7, 8, 9]])

In [125]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

### Numpy array selection 

In [129]:
arr = np.random.randint(0,101,10)
arr

array([64, 18, 67,  9, 79, 48, 69, 17, 65, 23])

In [131]:
bool_arr = arr > 50
bool_arr

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

    You can filter value in [] by list of boolean value

In [132]:
arr[bool_arr]

array([64, 67, 79, 69, 65])

### Numpy array Operation

In [135]:
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [141]:
arr + arr

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [144]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [147]:
arr * np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [148]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [149]:
arr ** 2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [150]:
np.sqrt(arr)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [152]:
np.max(arr),np.min(arr), np.min(arr), np.log(arr)

(1.0,
 1.0,
 1.0,
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))